/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Visual + navigation enrichment for the Help / Documentation page.
 *
 * Kept separate from the generated helpContent.ts so the documentation copy
 * (generated by scripts/gen-help-i18n.js) and the screenshot / deep-link config
 * can each evolve independently. HelpView merges this map onto HELP_SECTIONS by id.
 *
 * Screenshots: `src` points at a file under /public. The <ScreenshotPreview> lazy-loads
 * it and gracefully falls back to a styled placeholder when the file is absent — so the
 * page works today and you can drop real captures into public/help/ incrementally.
 * Recommended size ~1280×800 (16:10), <300KB each (WebP/PNG).
 *
 * Deep links:
 *  - kind 'view'  → in-app SPA view (home | market | hub | map | subscription | profile …)
 *  - kind 'route' → real Next route (/dashboard/*). `requiresDashboard` hides it from guests.
 *
 * All labels/captions are i18n keys — never hardcode visible text here.
 */

import type { HelpLink, HelpMedia } from './helpContent';

export interface HelpEnrichment {
  media?: HelpMedia[];
  links?: HelpLink[];
}

/** Convention: screenshots live at /public/help/<id>.webp (override per item if needed). */
const shot = (id: string): string => `/help/${id}.webp`;

/**
 * Feature flag — deep-link buttons whose `labelKey` is listed here are temporarily
 * hidden from the Help page (their definitions below stay intact for easy reuse).
 * To re-enable a button, remove its label key from this set.
 *
 * Currently disabled: "Open Profile" and "Open Subscription".
 */
const DISABLED_HELP_LINK_LABELS = new Set<HelpLink['labelKey']>([
  'helpLinkOpenProfile',
  'helpLinkOpenSubscription',
]);

/**
 * Returns the enrichment for a section with any feature-flagged links filtered out.
 * Use this (not HELP_ENRICHMENTS directly) anywhere links are rendered, so the flag
 * is honoured consistently. Navigation logic/routes are preserved — only UI is gated.
 */
export function getHelpEnrichment(id: string): HelpEnrichment | undefined {
  const raw = HELP_ENRICHMENTS[id];
  if (!raw) return undefined;
  if (!raw.links?.length || DISABLED_HELP_LINK_LABELS.size === 0) return raw;
  const links = raw.links.filter((l) => !DISABLED_HELP_LINK_LABELS.has(l.labelKey));
  return { ...raw, links };
}

export const HELP_ENRICHMENTS: Record<string, HelpEnrichment> = {
  overview: {
    media: [{ src: shot('home'), captionKey: 'helpCapHome', icon: 'Home' }],
    links: [{ kind: 'view', target: 'home', labelKey: 'helpLinkOpenHome', icon: 'Home' }],
  },
  entry: {
    media: [{ src: shot('home'), captionKey: 'helpCapLanding', icon: 'Home' }],
    links: [
      { kind: 'view', target: 'home', labelKey: 'helpLinkOpenHome', icon: 'Home' },
      { kind: 'view', target: 'market', labelKey: 'helpLinkOpenMarket', icon: 'Market' },
    ],
  },
  public: {
    media: [
      { src: shot('market'), captionKey: 'helpCapMarket', icon: 'Market' },
      { src: shot('hub'), captionKey: 'helpCapHub', icon: 'Hub' },
      { src: shot('stores'), captionKey: 'helpCapStores', icon: 'Location' },
    ],
    links: [
      { kind: 'view', target: 'market', labelKey: 'helpLinkOpenMarket', icon: 'Market' },
      { kind: 'view', target: 'hub', labelKey: 'helpLinkOpenHub', icon: 'Hub' },
      { kind: 'view', target: 'map', labelKey: 'helpLinkOpenStores', icon: 'Location' },
    ],
  },
  auth: {
    media: [{ src: shot('login'), captionKey: 'helpCapAuth', icon: 'Auth' }],
    links: [{ kind: 'view', target: 'login', labelKey: 'helpLinkOpenLogin', icon: 'Auth' }],
  },
  subscription: {
    media: [{ src: shot('subscription'), captionKey: 'helpCapSubscription', icon: 'Payment' }],
    links: [{ kind: 'view', target: 'subscription', labelKey: 'helpLinkOpenSubscription', icon: 'Payment' }],
  },
  account: {
    media: [{ src: shot('account'), captionKey: 'helpCapAccount', icon: 'Settings' }],
    links: [{ kind: 'view', target: 'profile', labelKey: 'helpLinkOpenProfile', icon: 'Settings' }],
  },
  dashboard: {
    media: [{ src: shot('dashboard'), captionKey: 'helpCapDashboard', icon: 'Dashboard' }],
    links: [{ kind: 'route', target: '/dashboard', labelKey: 'helpLinkOpenDashboard', icon: 'Dashboard', requiresDashboard: true }],
  },
  modules: {
    media: [
      { src: shot('dashboard-overview'), captionKey: 'helpCapOverviewModule', icon: 'Dashboard' },
      { src: shot('analytics'), captionKey: 'helpCapAnalytics', icon: 'ListChecks' },
      { src: shot('inventory'), captionKey: 'helpCapInventory', icon: 'Package' },
    ],
    links: [
      { kind: 'route', target: '/dashboard', labelKey: 'helpLinkOpenOverview', icon: 'Dashboard', requiresDashboard: true },
      { kind: 'route', target: '/dashboard/analytics', labelKey: 'helpLinkOpenAnalytics', icon: 'ListChecks', requiresDashboard: true },
      { kind: 'route', target: '/dashboard/inventory', labelKey: 'helpLinkOpenInventory', icon: 'Package', requiresDashboard: true },
    ],
  },
  'product-creation': {
    media: [{ src: shot('product-creation'), captionKey: 'helpCapProductCreation', icon: 'Package' }],
    links: [{ kind: 'route', target: '/dashboard/inventory', labelKey: 'helpLinkOpenInventory', icon: 'Package', requiresDashboard: true }],
  },
  'retailer-network': {
    media: [{ src: shot('retailer-network'), captionKey: 'helpCapRetailerNetwork', icon: 'Network' }],
    links: [{ kind: 'route', target: '/dashboard/manufacturer/retailers', labelKey: 'helpLinkOpenRetailers', icon: 'Network', requiresDashboard: true }],
  },
  'retailer-onboarding': {
    media: [{ src: shot('add-retailer'), captionKey: 'helpCapAddRetailer', icon: 'Users' }],
    links: [{ kind: 'route', target: '/dashboard/manufacturer/retailers', labelKey: 'helpLinkOpenRetailers', icon: 'Users', requiresDashboard: true }],
  },
  invite: {
    media: [{ src: shot('invite'), captionKey: 'helpCapInvite', icon: 'Share' }],
    links: [{ kind: 'route', target: '/dashboard/manufacturer/retailers', labelKey: 'helpLinkOpenRetailers', icon: 'Share', requiresDashboard: true }],
  },
  assignment: {
    media: [{ src: shot('assign-product'), captionKey: 'helpCapAssign', icon: 'Clipboard' }],
    links: [{ kind: 'route', target: '/dashboard/manufacturer/retailers', labelKey: 'helpLinkOpenRetailers', icon: 'Clipboard', requiresDashboard: true }],
  },
  'retailer-details': {
    media: [{ src: shot('retailer-details'), captionKey: 'helpCapRetailerDetails', icon: 'Users' }],
    links: [{ kind: 'route', target: '/dashboard/manufacturer/retailers', labelKey: 'helpLinkOpenRetailers', icon: 'Users', requiresDashboard: true }],
  },
  'subscription-mgmt': {
    media: [{ src: shot('subscription-mgmt'), captionKey: 'helpCapSubscriptionMgmt', icon: 'Payment' }],
    links: [{ kind: 'route', target: '/dashboard/subscription', labelKey: 'helpLinkOpenSubscription', icon: 'Payment', requiresDashboard: true }],
  },
  listing: {
    media: [{ src: shot('listing'), captionKey: 'helpCapListing', icon: 'ListChecks' }],
    links: [{ kind: 'route', target: '/dashboard/inventory', labelKey: 'helpLinkOpenInventory', icon: 'ListChecks', requiresDashboard: true }],
  },
  orders: {
    media: [{ src: shot('orders'), captionKey: 'helpCapOrders', icon: 'Orders' }],
    links: [{ kind: 'route', target: '/dashboard/orders', labelKey: 'helpLinkOpenOrders', icon: 'Orders', requiresDashboard: true }],
  },
  reviews: {
    media: [{ src: shot('reviews'), captionKey: 'helpCapReviews', icon: 'Review' }],
    links: [{ kind: 'route', target: '/dashboard/reviews', labelKey: 'helpLinkOpenReviews', icon: 'Review', requiresDashboard: true }],
  },
  'profile-settings': {
    media: [{ src: shot('profile'), captionKey: 'helpCapProfile', icon: 'Settings' }],
    links: [{ kind: 'route', target: '/dashboard/profile', labelKey: 'helpLinkOpenProfile', icon: 'Settings', requiresDashboard: true }],
  },
  settings: {
    media: [{ src: shot('settings'), captionKey: 'helpCapSettings', icon: 'Settings' }],
    links: [{ kind: 'route', target: '/dashboard/settings', labelKey: 'helpLinkOpenSettings', icon: 'Settings', requiresDashboard: true }],
  },
  architecture: {
    // No screenshot — the in-page layered diagram is the visual for this section.
    links: [{ kind: 'view', target: 'home', labelKey: 'helpLinkOpenHome', icon: 'Home' }],
  },
};
