/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Structured documentation content for the KrishiDukan Help / Documentation page.
 *
 * This is the single source of truth for the Help page body. It mirrors the full
 * "KrishiDukan Portal — Complete Functional Flow" reference document, section by
 * section, with NO content omitted.
 *
 * IMPORTANT (multilingual): every user-visible string is an i18n KEY, not literal
 * text. HelpView resolves each key through the existing `useI18n().t()` hook, so the
 * whole page (titles, summaries, paragraphs, lists, steps, chips, notes and the
 * architecture map) switches with the selected portal language exactly like the
 * rest of the platform. To add a future documentation module, register its strings
 * in app/i18n/translations.ts (en/mr/hi) and reference the keys here.
 *
 * Block model (each holds translation key(s), never literal copy):
 *  - 'p'      → a paragraph of prose            ({ key })
 *  - 'sub'    → a sub-heading inside a section   ({ key })
 *  - 'note'   → a highlighted callout            ({ key })
 *  - 'list'   → a bulleted list                  ({ keys[] })
 *  - 'steps'  → an ordered (numbered) list       ({ keys[] })
 *  - 'states' → a row of small "state/tag" chips ({ keys[] })
 *  - 'flow'   → an arrow-connected layer diagram ({ layers: { titleKey, keys[] }[] })
 *
 * THIS FILE IS GENERATED by scripts/gen-help-i18n.js — edit the generator, not this.
 */

import type { translations } from '../i18n/translations';

type TranslationKey = keyof typeof translations['en'];

export type HelpBlock =
  | { kind: 'p'; key: TranslationKey }
  | { kind: 'sub'; key: TranslationKey }
  | { kind: 'note'; key: TranslationKey }
  | { kind: 'list'; keys: TranslationKey[] }
  | { kind: 'steps'; keys: TranslationKey[] }
  | { kind: 'states'; keys: TranslationKey[] }
  | { kind: 'flow'; layers: { titleKey: TranslationKey; keys: TranslationKey[] }[] };

/**
 * A visual preview for a section/subsection. `src` points at a screenshot under
 * /public (served from the site root). The renderer lazy-loads it and falls back
 * to a styled icon placeholder if the file is not present yet — so the page is
 * "screenshot-ready" and you can drop real captures into public/help/ over time.
 */
export interface HelpMedia {
  /** Public path to the screenshot, e.g. '/help/market.webp'. */
  src: string;
  /** i18n key for the caption shown under the preview. */
  captionKey: TranslationKey;
  /** Optional icon override for the fallback placeholder (defaults to the section icon). */
  icon?: keyof typeof import('../constants')['ICONS'];
}

/**
 * A deep link / navigation action for a section.
 *  - kind 'view'  → an in-app SPA view handled by the parent's onNavigate (e.g. 'market').
 *  - kind 'route' → a real Next.js route pushed via the router (e.g. '/dashboard/inventory').
 * `requiresDashboard` actions are only shown to logged-in retailers/manufacturers
 * so guests are never bounced into the paywall/login from the docs.
 */
export interface HelpLink {
  kind: 'view' | 'route';
  /** The SPA view id (for 'view') or the route path (for 'route'). */
  target: string;
  /** i18n key for the button label. */
  labelKey: TranslationKey;
  /** Icon key from ICONS; defaults to an arrow. */
  icon?: keyof typeof import('../constants')['ICONS'];
  /** When true, only render for logged-in retailer/manufacturer users. */
  requiresDashboard?: boolean;
}

export interface HelpSection {
  /** Stable anchor id used for the URL hash, TOC links and scroll-spy. */
  id: string;
  /** i18n key for the section title shown in the TOC and section header. */
  titleKey: TranslationKey;
  /** Icon key from ICONS in app/constants.ts. */
  icon: keyof typeof import('../constants')['ICONS'];
  /** i18n key for the short one-line summary shown under the section title. */
  summaryKey: TranslationKey;
  /** Ordered content blocks rendered inside the section body. */
  blocks: HelpBlock[];
  /** Optional screenshot/preview(s) for this section. */
  media?: HelpMedia[];
  /** Optional deep-link / navigation actions for this section. */
  links?: HelpLink[];
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: 'overview',
    titleKey: 'helpSecOverview',
    icon: 'Docs',
    summaryKey: 'helpSumOverview',
    blocks: [
      { kind: 'p', key: 'helpOvP1' },
      { kind: 'p', key: 'helpOvP2' },
      { kind: 'note', key: 'helpOvNote' },
    ],
  },
  {
    id: 'entry',
    titleKey: 'helpSecEntry',
    icon: 'Compass',
    summaryKey: 'helpSumEntry',
    blocks: [
      { kind: 'sub', key: 'helpEntrySub1' },
      { kind: 'p', key: 'helpEntryP1' },
      { kind: 'list', keys: ['helpTxtHome', 'helpTxtMarket', 'helpTxtHub', 'helpTxtStores'] },
      { kind: 'sub', key: 'helpEntrySub2' },
      { kind: 'p', key: 'helpEntryP2' },
      { kind: 'list', keys: ['helpEntryI1', 'helpEntryI2', 'helpEntryI3', 'helpEntryI4', 'helpEntryI5'] },
    ],
  },
  {
    id: 'public',
    titleKey: 'helpSecPublic',
    icon: 'Home',
    summaryKey: 'helpSumPublic',
    blocks: [
      { kind: 'sub', key: 'helpPubSubA' },
      { kind: 'p', key: 'helpPubAP1' },
      { kind: 'p', key: 'helpTxtUserCan' },
      { kind: 'list', keys: ['helpPubAI1', 'helpPubAI2', 'helpPubAI3', 'helpPubAI4', 'helpPubAI5', 'helpPubAI6'] },
      { kind: 'note', key: 'helpPubANote' },
      { kind: 'sub', key: 'helpPubSubB' },
      { kind: 'p', key: 'helpPubBP1' },
      { kind: 'p', key: 'helpTxtUserCan' },
      { kind: 'list', keys: ['helpPubBI1', 'helpPubBI2', 'helpPubBI3', 'helpPubBI4', 'helpPubBI5', 'helpPubBI6'] },
      { kind: 'p', key: 'helpPubBP2' },
      { kind: 'list', keys: ['helpPubBI7', 'helpPubBI8', 'helpPubBI9'] },
      { kind: 'sub', key: 'helpPubSubC' },
      { kind: 'p', key: 'helpPubCP1' },
      { kind: 'p', key: 'helpTxtUserCan' },
      { kind: 'list', keys: ['helpPubCI1', 'helpPubCI2', 'helpPubCI3', 'helpPubCI4'] },
      { kind: 'p', key: 'helpPubCP2' },
      { kind: 'states', keys: ['helpStEstablishment', 'helpStVegetative', 'helpStFlowering', 'helpStDevelopment', 'helpStHarvesting'] },
      { kind: 'note', key: 'helpPubCNote' },
      { kind: 'sub', key: 'helpPubSubD' },
      { kind: 'p', key: 'helpPubDP1' },
      { kind: 'p', key: 'helpPubDP2' },
      { kind: 'list', keys: ['helpPubDI1', 'helpPubDI2', 'helpPubDI3', 'helpPubDI4', 'helpPubDI5', 'helpPubDI6'] },
      { kind: 'note', key: 'helpPubDNote' },
    ],
  },
  {
    id: 'auth',
    titleKey: 'helpSecAuth',
    icon: 'Auth',
    summaryKey: 'helpSumAuth',
    blocks: [
      { kind: 'sub', key: 'helpAuthSub1' },
      { kind: 'p', key: 'helpAuthP1' },
      { kind: 'list', keys: ['helpTxtFarmer', 'helpTxtRetailer', 'helpTxtManufacturer'] },
      { kind: 'sub', key: 'helpAuthSub2' },
      { kind: 'steps', keys: ['helpAuthS1', 'helpAuthS2', 'helpAuthS3', 'helpAuthS4', 'helpAuthS5'] },
      { kind: 'sub', key: 'helpAuthSub3' },
      { kind: 'list', keys: ['helpAuthI1', 'helpAuthI2', 'helpAuthI3'] },
    ],
  },
  {
    id: 'subscription',
    titleKey: 'helpSecSubscription',
    icon: 'Payment',
    summaryKey: 'helpSumSubscription',
    blocks: [
      { kind: 'sub', key: 'helpSubsSub1' },
      { kind: 'p', key: 'helpSubsP1' },
      { kind: 'sub', key: 'helpSubsSub2' },
      { kind: 'states', keys: ['helpSubsPlan1', 'helpSubsPlan2', 'helpSubsPlan3', 'helpSubsPlan4'] },
      { kind: 'sub', key: 'helpSubsSub3' },
      { kind: 'note', key: 'helpSubsNote1' },
      { kind: 'p', key: 'helpSubsP2' },
      { kind: 'list', keys: ['helpSubsI1', 'helpSubsI2'] },
      { kind: 'sub', key: 'helpSubsSub4' },
      { kind: 'p', key: 'helpSubsP3' },
      { kind: 'list', keys: ['helpSubsI3', 'helpSubsI4', 'helpSubsI5', 'helpSubsI6'] },
      { kind: 'sub', key: 'helpSubsSub5' },
      { kind: 'p', key: 'helpSubsP4' },
      { kind: 'list', keys: ['helpSubsI7', 'helpSubsI8', 'helpSubsI9', 'helpSubsI10'] },
    ],
  },
  {
    id: 'account',
    titleKey: 'helpSecAccount',
    icon: 'Settings',
    summaryKey: 'helpSumAccount',
    blocks: [
      { kind: 'sub', key: 'helpAccSub1' },
      { kind: 'p', key: 'helpTxtUserCan' },
      { kind: 'list', keys: ['helpAccI1', 'helpAccI2', 'helpAccI3', 'helpAccI4'] },
      { kind: 'note', key: 'helpAccNote' },
    ],
  },
  {
    id: 'dashboard',
    titleKey: 'helpSecDashboard',
    icon: 'Dashboard',
    summaryKey: 'helpSumDashboard',
    blocks: [
      { kind: 'p', key: 'helpDashP1' },
      { kind: 'note', key: 'helpDashNote' },
      { kind: 'p', key: 'helpTxtUserCan' },
      { kind: 'list', keys: ['helpDashI1', 'helpDashI2', 'helpDashI3', 'helpDashI4', 'helpDashI5', 'helpDashI6'] },
      { kind: 'p', key: 'helpDashP2' },
      { kind: 'list', keys: ['helpDashI7'] },
    ],
  },
  {
    id: 'modules',
    titleKey: 'helpSecModules',
    icon: 'ListChecks',
    summaryKey: 'helpSumModules',
    blocks: [
      { kind: 'sub', key: 'helpModSubA' },
      { kind: 'p', key: 'helpModP1' },
      { kind: 'list', keys: ['helpModI1', 'helpModI2', 'helpModI3', 'helpModI4', 'helpModI5', 'helpModI6'] },
      { kind: 'p', key: 'helpModP2' },
      { kind: 'list', keys: ['helpModI7', 'helpModI8', 'helpModI9', 'helpModI10'] },
      { kind: 'note', key: 'helpModNoteA' },
      { kind: 'sub', key: 'helpModSubB' },
      { kind: 'p', key: 'helpModP3' },
      { kind: 'list', keys: ['helpModI11', 'helpModI12', 'helpModI13', 'helpModI14', 'helpModI15'] },
      { kind: 'note', key: 'helpModNoteB' },
      { kind: 'p', key: 'helpModP4' },
      { kind: 'list', keys: ['helpModI16', 'helpModI17', 'helpModI18', 'helpModI19'] },
      { kind: 'sub', key: 'helpModSubC' },
      { kind: 'p', key: 'helpModP5' },
      { kind: 'p', key: 'helpTxtUserCan' },
      { kind: 'list', keys: ['helpModI20', 'helpModI21', 'helpModI22', 'helpModI23', 'helpModI24', 'helpModI25'] },
      { kind: 'p', key: 'helpModP6' },
      { kind: 'states', keys: ['helpModSt1', 'helpModSt2', 'helpModSt3', 'helpModSt4', 'helpModSt5', 'helpModSt6', 'helpModSt7'] },
    ],
  },
  {
    id: 'product-creation',
    titleKey: 'helpSecProductCreation',
    icon: 'Package',
    summaryKey: 'helpSumProductCreation',
    blocks: [
      { kind: 'sub', key: 'helpPcSub1' },
      { kind: 'p', key: 'helpPcP1' },
      { kind: 'list', keys: ['helpPcI1', 'helpPcI2', 'helpPcI3', 'helpPcI4', 'helpPcI5'] },
      { kind: 'sub', key: 'helpPcSub2' },
      { kind: 'p', key: 'helpPcP2' },
      { kind: 'states', keys: ['helpPcSt1', 'helpPcSt2', 'helpPcSt3', 'helpPcSt4', 'helpPcSt5'] },
      { kind: 'p', key: 'helpPcP3' },
      { kind: 'list', keys: ['helpPcI6', 'helpPcI7'] },
      { kind: 'sub', key: 'helpPcSub3' },
      { kind: 'p', key: 'helpPcP4' },
      { kind: 'list', keys: ['helpPcI8', 'helpPcI9'] },
      { kind: 'note', key: 'helpPcNote' },
      { kind: 'sub', key: 'helpPcSub4' },
      { kind: 'p', key: 'helpPcP5' },
      { kind: 'list', keys: ['helpPcI10', 'helpPcI11'] },
    ],
  },
  {
    id: 'retailer-network',
    titleKey: 'helpSecRetailerNetwork',
    icon: 'Network',
    summaryKey: 'helpSumRetailerNetwork',
    blocks: [
      { kind: 'p', key: 'helpRnP1' },
      { kind: 'sub', key: 'helpRnSub1' },
      { kind: 'list', keys: ['helpRnI1', 'helpRnI2', 'helpRnI3', 'helpRnI4'] },
      { kind: 'sub', key: 'helpRnSub2' },
      { kind: 'states', keys: ['helpRnSt1', 'helpRnSt2', 'helpRnSt3'] },
    ],
  },
  {
    id: 'retailer-onboarding',
    titleKey: 'helpSecRetailerOnboarding',
    icon: 'Users',
    summaryKey: 'helpSumRetailerOnboarding',
    blocks: [
      { kind: 'sub', key: 'helpRoSubA' },
      { kind: 'p', key: 'helpRoP1' },
      { kind: 'list', keys: ['helpRoI1', 'helpRoI2', 'helpRoI3', 'helpRoI4', 'helpRoI5', 'helpRoI6', 'helpRoI7', 'helpRoI8'] },
      { kind: 'p', key: 'helpRoP2' },
      { kind: 'list', keys: ['helpRoI9', 'helpRoI10', 'helpRoI11'] },
      { kind: 'p', key: 'helpRoP3' },
      { kind: 'list', keys: ['helpRoI12', 'helpRoI13', 'helpRoI14'] },
      { kind: 'p', key: 'helpRoP4' },
      { kind: 'list', keys: ['helpRoI15', 'helpRoI16', 'helpRoI17'] },
      { kind: 'sub', key: 'helpRoSubB' },
      { kind: 'p', key: 'helpRoP5' },
      { kind: 'list', keys: ['helpRoI18', 'helpRoI19', 'helpRoI20'] },
    ],
  },
  {
    id: 'invite',
    titleKey: 'helpSecInvite',
    icon: 'Share',
    summaryKey: 'helpSumInvite',
    blocks: [
      { kind: 'p', key: 'helpInvP1' },
      { kind: 'list', keys: ['helpInvI1', 'helpInvI2', 'helpInvI3', 'helpInvI4'] },
      { kind: 'note', key: 'helpInvNote' },
    ],
  },
  {
    id: 'assignment',
    titleKey: 'helpSecAssignment',
    icon: 'Clipboard',
    summaryKey: 'helpSumAssignment',
    blocks: [
      { kind: 'p', key: 'helpAsP1' },
      { kind: 'list', keys: ['helpAsI1', 'helpAsI2'] },
      { kind: 'p', key: 'helpAsP2' },
      { kind: 'sub', key: 'helpAsSub1' },
      { kind: 'list', keys: ['helpAsI3', 'helpAsI4', 'helpAsI5'] },
    ],
  },
  {
    id: 'retailer-details',
    titleKey: 'helpSecRetailerDetails',
    icon: 'Users',
    summaryKey: 'helpSumRetailerDetails',
    blocks: [
      { kind: 'sub', key: 'helpRdSub1' },
      { kind: 'list', keys: ['helpRdI1', 'helpRdI2', 'helpRdI3', 'helpRdI4', 'helpRdI5', 'helpRdI6', 'helpRdI7', 'helpRdI8', 'helpRdI9'] },
      { kind: 'sub', key: 'helpRdSub2' },
      { kind: 'list', keys: ['helpRdI10', 'helpRdI11'] },
      { kind: 'sub', key: 'helpRdSub3' },
      { kind: 'list', keys: ['helpRdI12', 'helpRdI13', 'helpRdI14', 'helpRdI15'] },
    ],
  },
  {
    id: 'subscription-mgmt',
    titleKey: 'helpSecSubscriptionMgmt',
    icon: 'Payment',
    summaryKey: 'helpSumSubscriptionMgmt',
    blocks: [
      { kind: 'sub', key: 'helpSmSub1' },
      { kind: 'list', keys: ['helpSmI1', 'helpSmI2', 'helpSmI3', 'helpSmI4'] },
      { kind: 'sub', key: 'helpSmSub2' },
      { kind: 'p', key: 'helpSmP1' },
      { kind: 'list', keys: ['helpSmI5', 'helpSmI6', 'helpSmI7'] },
      { kind: 'sub', key: 'helpSmSub3' },
      { kind: 'list', keys: ['helpSmI8', 'helpSmI9'] },
      { kind: 'sub', key: 'helpSmSub4' },
      { kind: 'list', keys: ['helpSmI10', 'helpSmI11', 'helpSmI12'] },
    ],
  },
  {
    id: 'listing',
    titleKey: 'helpSecListing',
    icon: 'ListChecks',
    summaryKey: 'helpSumListing',
    blocks: [
      { kind: 'sub', key: 'helpLsSub1' },
      { kind: 'list', keys: ['helpLsI1', 'helpLsI2', 'helpLsI3', 'helpLsI4', 'helpLsI5'] },
      { kind: 'sub', key: 'helpLsSub2' },
      { kind: 'states', keys: ['helpLsSt1', 'helpLsSt2', 'helpLsSt3'] },
      { kind: 'sub', key: 'helpLsSub3' },
      { kind: 'p', key: 'helpLsP1' },
      { kind: 'list', keys: ['helpLsI6', 'helpLsI7'] },
    ],
  },
  {
    id: 'orders',
    titleKey: 'helpSecOrders',
    icon: 'Orders',
    summaryKey: 'helpSumOrders',
    blocks: [
      { kind: 'sub', key: 'helpOrSub1' },
      { kind: 'steps', keys: ['helpOrS1', 'helpOrS2', 'helpOrS3'] },
      { kind: 'sub', key: 'helpOrSub2' },
      { kind: 'p', key: 'helpOrP1' },
      { kind: 'list', keys: ['helpOrI1', 'helpOrI2', 'helpOrI3', 'helpOrI4'] },
      { kind: 'note', key: 'helpOrNote' },
    ],
  },
  {
    id: 'reviews',
    titleKey: 'helpSecReviews',
    icon: 'Review',
    summaryKey: 'helpSumReviews',
    blocks: [
      { kind: 'sub', key: 'helpRvSub1' },
      { kind: 'steps', keys: ['helpRvS1', 'helpRvS2', 'helpRvS3'] },
      { kind: 'p', key: 'helpRvP1' },
      { kind: 'list', keys: ['helpRvI1', 'helpRvI2'] },
      { kind: 'note', key: 'helpRvNote' },
    ],
  },
  {
    id: 'profile-settings',
    titleKey: 'helpSecProfileSettings',
    icon: 'Settings',
    summaryKey: 'helpSumProfileSettings',
    blocks: [
      { kind: 'sub', key: 'helpPsSub1' },
      { kind: 'list', keys: ['helpPsI1', 'helpPsI2', 'helpPsI3', 'helpPsI4', 'helpPsI5', 'helpPsI6'] },
      { kind: 'sub', key: 'helpPsSub2' },
      { kind: 'list', keys: ['helpPsI7', 'helpPsI8', 'helpPsI9', 'helpPsI10'] },
      { kind: 'sub', key: 'helpPsSub3' },
      { kind: 'states', keys: ['helpPsSt1', 'helpPsSt2', 'helpPsSt3', 'helpPsSt4'] },
    ],
  },
  {
    id: 'settings',
    titleKey: 'helpSecSettings',
    icon: 'Settings',
    summaryKey: 'helpSumSettings',
    blocks: [
      { kind: 'sub', key: 'helpSeSub1' },
      { kind: 'list', keys: ['helpSeI1', 'helpSeI2', 'helpSeI3', 'helpSeI4'] },
      { kind: 'sub', key: 'helpSeSub2' },
      { kind: 'list', keys: ['helpSeI5', 'helpSeI6', 'helpSeI7'] },
      { kind: 'sub', key: 'helpSeSub3' },
      { kind: 'list', keys: ['helpSeI8', 'helpSeI9'] },
    ],
  },
  {
    id: 'architecture',
    titleKey: 'helpSecArchitecture',
    icon: 'Network',
    summaryKey: 'helpSumArchitecture',
    blocks: [
      { kind: 'p', key: 'helpArP1' },
      {
      kind: 'flow',
      layers: [
        { titleKey: 'helpArL1', keys: ['helpTxtHome', 'helpTxtMarket', 'helpTxtHub', 'helpTxtStores'] },
        { titleKey: 'helpArL2', keys: ['helpArL2a', 'helpArL2b', 'helpArL2c'] },
        { titleKey: 'helpArL3', keys: ['helpArL3a', 'helpArL3b', 'helpArL3c'] },
        { titleKey: 'helpArL4', keys: ['helpArL4a', 'helpArL4b', 'helpArL4c', 'helpArL4d', 'helpArL4e', 'helpArL4f', 'helpArL4g', 'helpArL4h', 'helpArL4i'] },
        { titleKey: 'helpArL5', keys: ['helpArL5a', 'helpArL5b', 'helpArL5c', 'helpArL5d', 'helpArL5e'] },
        { titleKey: 'helpArL6', keys: ['helpArL6a', 'helpArL6b', 'helpArL6c', 'helpArL6d', 'helpArL6e', 'helpArL6f'] },
      ],
    },
    ],
  },
];
